### ISSUE TITLE
Updating to latest Cake Release

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Gradle#12]
@abeggchr are you still in a position to maintain this addin?

During the recent audit, it was found that this addin is targetting 0.15.0 of Cake (which is quite a few releases behind).  If you are no longer in a position to maintain this addin, would you be interested in moving it to the Cake-Contrib Organisation, where it could be opened up to the Community?

**Comment by abeggchr** [comment]
@gep13 Yes, we can move it to the cake-contrib organisation. How shall I proceed?

**Comment by gep13** [comment]
@abeggchr that is great news!  In order to get the repository into the Organisation, it first has to be transferred to someone how has access to move it into the Organisation, i.e. me.  So, if you could transfer the repository to me, I can then get it moved into the Organisation, and then set you up with correct permissions, etc.

Let me know if you have any questions.

**Comment by abeggchr** [comment]
@gep13 cannot transfer it to you because gep13/cake-gradle repo already exists.

**Comment by gep13** [comment]
@abeggchr ah, that happens when I have already forked the existing repository.  I have now deleted my fork, which should allow you to transfer it to my GitHub account.  Can you please try again?  Thanks for getting back to me about this, I really appreciate it!

**Comment by gep13** [comment]
@abeggchr just wanted to follow up with this again.  Are you in a position to attempt the transfer again?

**Comment by abeggchr** [comment]
@gep13 repo is currently being transferred

**Comment by gep13** [comment]
@abeggchr thank you for doing this.  I have completed the transfer of the repository into the Cake Contrib Organisation.  Thanks again for doing this.

Are you in a position to update this repository to the latest Cake recommended Cake release, or would you like some help to get this done?

**Comment by abeggchr** [comment]
I would like someone else to take this over.

**Comment by nils-a** [comment]
@abeggchr I'd be willing to take this on if you are still looking for someone to maintain it.

**Comment by gep13** [comment]
@nils-a this sounds like a plan to me! :+1:

**Comment by gep13** [comment]
@abeggchr I am going to add @nils-a as a contributor to this repository, with permissions to make commits into the repository.

**Comment by nils-a** [comment]
@gep13 I have updated the project structure in `develop` to match current cake-contrib best practices.
If you would be so kind as to enable appVeyor, I'd release the [0.2.0](https://github.com/cake-contrib/cake-gradle/milestone/1). When that is done, I'll update to current Cake.Core and release [0.3.0](https://github.com/cake-contrib/cake-gradle/milestone/2)

**Comment by gep13** [comment]
@nils-a the AppVeyor build for Cake.Gradle has been created:

https://ci.appveyor.com/project/cakecontrib/cake-gradle

And you should have access to it.

Let me know if you have any questions.
