### ISSUE TITLE
Add documentation XML to NuGet package

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Gradle#20]
The addin contains XML comments for aliases, but doesn't ship with the documentation XML file. Therefore comments can't be shown on Cake website (e.g. https://cakebuild.net/extensions/cake-gradle/).
To have aliases documented on the Cake website the NuGet package needs to ship with the documentation XML in the NuGet package.

**Comment by nils-a** [comment]
Way ahead of you 😇 check https://github.com/cake-contrib/Cake.Gradle/actions/runs/424350746#artifacts

**Comment by nils-a** [comment]
This was solved in [(maint) updated project-setup](https://github.com/cake-contrib/Cake.Gradle/commit/e1d32e32d1ccd8f0661113ff268bf1ddc81db1d6)
