### ISSUE TITLE
Cake.Gradle does not work, if gradle was installed globally using chocolatey

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Gradle#28]
currently, if `gradle` is installed on the system and no `gradlew` is present in the project either `gradle.bat` or `gradle` are run (depending on windows/no windows).

If `gradle` was installed using [chocolatey](https://chocolatey.org/) `gradle` is present, however it is available via a `gradle.exe`-shim and so `Cake.Gradle` reports `Gradle Runner: Could not locate executable.`

**Comment by gep13** [comment]
This should be a case of modifying this method:

https://github.com/cake-contrib/Cake.Gradle/blob/develop/src/Cake.Gradle/GradleRunner.cs#L146-L156

Right?

**Comment by nils-a** [comment]
@gep13 exactly. Will fix this tonight, if have the time.

**Comment by gep13** [comment]
@nils-a perfect! I am hoping to spend some time on the Visual Studio Extension tonight 😄
