### ISSUE TITLE
Neither codecov, nor coveralls show coverage.

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Gradle#32]
* (codecov)[https://codecov.io/gh/cake-contrib/Cake.Gradle] shows nothing (though commits are listed), clicking on a commit shows `There was an error processing coverage reports.`
* (coveralls)[https://coveralls.io/github/cake-contrib/cake-gradle] shows %0 coverage. As with codecov, the builds are listed but the report seemingly contains no data.

**Comment by gep13** [comment]
Have you enabled deterministic builds? I never not seeing anything being reported until everything in this area was turned on fully.

**Comment by nils-a** [comment]
Interesting point. I have set `shouldUseDeterministicBuilds: true` but comparing this project to the others I have missed (Directory.Build.targets)[https://github.com/cake-contrib/Cake.7zip/blob/develop/src/Directory.Build.targets].

Do we have the steps for enabling deterministic builds documented somewhere?

**Comment by gep13** [comment]
I thought we did.

@AdmiringWorm created a task in Cake.Recipe (I forget the exact name) that you can run which sets everything up.

**Comment by AdmiringWorm** [comment]
There isn't really any documentation on enabling deterministic builds (by default, cake.recipe have it enabled by default though).

However, there are some workarounds that need to be done in some rare cases,
like enabling `shouldRunDotNetCorePack` (using raw nuspec can be used, but not sure what is necessary to allow it).
To enable both deterministic and coverlet builds, the easiest way to have it work is to run either the `Enable-DeterministicBuild` or the `Enable-Coverlet` tasks (just once, then check in the changes made).

These two tasks are the same, one is just an alias for the other one.

**Comment by nils-a** [comment]
Yes. `Enable-Coverlet` is indeed the task which made it work just now. Thanks.
